# ---------------------------------------------------------------------------------
#     _   _ ___________  ___   _   _ _____
#    | | | |  ___| ___ \/ _ \ | \ | |  __ \
#    | | | | |__ | |_/ / /_\ \|  \| | |  \/
#    | | | |  __||    /|  _  || . ` | | __
#    \ \_/ / |___| |\ \| | | || |\  | |_\ \
#     \___/\____/\_| \_\_| |_/\_| \_/\____/
#
#      Simple Chat Formatting Plugin
# ---------------------------------------------------------------------------------

chat-format: "§8➛§f"  # Dark gray arrow followed by white reset for the chat message
